### ISSUE TITLE
FIO JSON output format has changed.

### ISSUE THREAD

**Issue by tigerquoll** [cloudera/partner-engineering#1]
Parsing scripts break on the latest version of FIO Json output.

**Comment by technmsg** [comment]
@tigerquoll can you provide the output of the following?

`fio --version`

**Comment by tigerquoll** [comment]
Good call - it was as the earlier version of FIO in the mix - RHEl 7.4 repos that our boxes were talking to used FIO 2.x, while the RHEL 7.5 box that were using as the master automatically pulled down 3.x.  FIO does not seem to detect when it is trying to remotely drive an older version - it will silently fail.  Updating all FIO versions to the same 3.x version fixed the issue.
